// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBODT2ofmrjddKDzeqJ0wBwyGT-IXLjxe8',
    appId: '1:629288225882:web:003961cd74db55b6d21c63',
    messagingSenderId: '629288225882',
    projectId: 'chat-app-abo-ramdan',
    authDomain: 'chat-app-abo-ramdan.firebaseapp.com',
    storageBucket: 'chat-app-abo-ramdan.firebasestorage.app',
    measurementId: 'G-4PF11SQFPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_j_MIYzOejIqHEeyWWH4R1HyGX_Ua1Uw',
    appId: '1:629288225882:android:49f1a49e83ef139ed21c63',
    messagingSenderId: '629288225882',
    projectId: 'chat-app-abo-ramdan',
    storageBucket: 'chat-app-abo-ramdan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeCof8XgRd9V1nEi2CrTC5PL2-GSn4klo',
    appId: '1:629288225882:ios:8341ffe49429331fd21c63',
    messagingSenderId: '629288225882',
    projectId: 'chat-app-abo-ramdan',
    storageBucket: 'chat-app-abo-ramdan.firebasestorage.app',
    iosBundleId: 'com.chatapp.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBODT2ofmrjddKDzeqJ0wBwyGT-IXLjxe8',
    appId: '1:629288225882:web:297f2306e3505216d21c63',
    messagingSenderId: '629288225882',
    projectId: 'chat-app-abo-ramdan',
    authDomain: 'chat-app-abo-ramdan.firebaseapp.com',
    storageBucket: 'chat-app-abo-ramdan.firebasestorage.app',
    measurementId: 'G-WXYDYE1Y2R',
  );

}