// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkDa5e8m-vquTCTXFiobcRKnHjHhV4boQ',
    appId: '1:792611509359:web:19e602252fef62a7f3299a',
    messagingSenderId: '792611509359',
    projectId: 'chatapp1-70a1d',
    authDomain: 'chatapp1-70a1d.firebaseapp.com',
    storageBucket: 'chatapp1-70a1d.firebasestorage.app',
    measurementId: 'G-KZYZT16SYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZeGdfPrTw-tXlCxdz2Lnktzt2_oCEWok',
    appId: '1:792611509359:android:5523dec4fbb4269ef3299a',
    messagingSenderId: '792611509359',
    projectId: 'chatapp1-70a1d',
    storageBucket: 'chatapp1-70a1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_i3Yzpw6wOfHIMcQR8q81gEgSzV-knpY',
    appId: '1:792611509359:ios:120b2c70ab68e58cf3299a',
    messagingSenderId: '792611509359',
    projectId: 'chatapp1-70a1d',
    storageBucket: 'chatapp1-70a1d.firebasestorage.app',
    iosBundleId: 'com.chatapp.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkDa5e8m-vquTCTXFiobcRKnHjHhV4boQ',
    appId: '1:792611509359:web:7aa0235f01143129f3299a',
    messagingSenderId: '792611509359',
    projectId: 'chatapp1-70a1d',
    authDomain: 'chatapp1-70a1d.firebaseapp.com',
    storageBucket: 'chatapp1-70a1d.firebasestorage.app',
    measurementId: 'G-XGE3WQ46L5',
  );
}
